### ISSUE TITLE
Fix boolean attribute delegates

### ISSUE THREAD

**Issue by hpehl** [jwstegemann/fritz2#171] opened 2020-09-10 21:34 UTC
**Describe the bug**
Many tags have boolean attributes like `button.disabled`. These attributes are currently handled by `AttributeDelegate`. This class sets the attribute value to `true` resp `false`:

```html
<button disabled="true">Click me!</button>
<button disabled="false">Click me!</button>
```

**Expected behavior**
Instead of setting the attribute value, the attribute itself should be added / removed for boolean attributes:

```html
<button>Click me!</button>
<button disabled>Click me!</button>
```

**Comment by chausknecht** [comment] 2020-10-08 16:42
This seems to be not fixed yet!

### Current behavior
The attribute is *still* set, if there are **more** than one ~~boolean~~ _arbitrary typed_ attribute! (The boolean value is missing though; it's only the attribute with an empty value)

```html
<button disabled="" autofocus="">Click me!</button>
                    ^^^^^^^^^^^^
                    another attribute

<input placeholder="fill it out!" readonly="">
       ^^^^^^^^^^^^
       another attribute
```

### Expected behavior
Instead of setting the attribute value, the attribute itself should be added / removed for boolean attributes:

```html
<button>Click me!</button>
<button disabled autofocus>Click me!</button>
<input placeholder="fill it out!" readonly>
```

**Comment by jamowei** [comment] 2020-10-10 12:28
Ok, problem solved. The actual code in `master` branch is correct and works like expected. Only the last `publish` run hasn't published the correct version after merging the PR. So when using the remote lib of fritz2 `0.8-SNAPSHOT` the behavior at this point is wrong. I did a re-run of this task and now the correct version is published. @chausknecht please update your dependencies then the problem will be fixed. You can also merge the current `master` into your branch, this should fix your problem too.

**Closed by jamowei** 2020-10-10 12:28 UTC

**Comment by hpehl** [comment] 2020-10-10 19:53
Good to hear. I thought something was wrong with my PR.

**Comment by chausknecht** [comment] 2020-10-12 08:15
I was indeed wrong with my assumption (based upon a false deduction by myself), that the serialization in the form ``attr=""`` was a problem - this is just how *Firefox* serializes boolean attributes if there is *more* than one attribute within a DOM element. But this complies to the [specs](https://html.spec.whatwg.org/#boolean-attributes) - even though it feels inconsistent and clumsy imho!
