### ISSUE TITLE
Events are passed to parent elements

### ISSUE THREAD

**Issue by TRaafCF** [jwstegemann/fritz2#329] opened 2021-04-01 13:13 UTC
When using the "clicks" DomListener (I haven't tested this for other Listeners, yet) in a clickButton or a similar  HTMLElement the events are set on its parent element. This leads to unexpected behaviour whenever two clickable elements share the same parent, in which case a click on the parent element will trigger both events at the same time.

**Example code to reproduce**
```
div {
    clickButton {
        text("First Button")
        clicks handledBy someHandler
    }
    clickButton {
        text("Second Button")
        clicks handledBy someOtherHandler
    }
}
``` 
**Example Screenshot**
![grafik](https://user-images.githubusercontent.com/81757717/113298864-8e323100-92fc-11eb-9d33-1cd61d9722db.png)

**Version used**
v0.9.1

**Browser**
Firefox 87.0

**Comment by chausknecht** [comment] 2021-04-01 13:52
This is not a bug! Your observation is based upon false usage of our components paired with some weakness of our DSL.

Let me explain this to you :-)

First of all, the clou of the ``clickButton`` - in contrast to the ``pushButton``! - is, that the factory function returns the event (``DomListener<MouseEvent, HTMLButtonElement>``) created by a click already itself, so you can *directly* combine it with an appropriate handler. (We call this [_structural composition_](https://docs.fritz2.dev/ComponentLibrary.html#composition-on-steroids)):
```kotlin
clickButton {
    text("Third click")
} handledBy toast {
    content { div { +"Third click" } }
}
```

So there is no need to grab the event from inside the component.

If you would like to do that, you should use our ``pushButton``:
```kotlin
pushButton {
    text("First Button")
    events { // use the specific *context* - almost all components expose such an ``events`` context
        clicks handledBy toast {
            content { div { +"First Button" } }
        }
    }
}
```
The key difference is, that the event from the _underlying_ button element is only exposed from within the ``events`` context.

Your code does something different: You take the ``click`` event from the *encapsulating* receiver, which is the surrounding ``div``, and bind it to a handler. And you do this twice! So in reality the framework does exactly what you tell it: React to *one* click event (on the ``div``) and pass a value to the two flows bound to it.

It might become more clear, if you put some padding into your div, and click beside the buttons:
![grafik](https://user-images.githubusercontent.com/70946811/113304024-eb7cb100-9301-11eb-85ff-c959553bcf04.png)
```kotlin
lineUp({
    padding { huge }
    background { color { gray300 } }
    alignContent { spaceAround }
}) {
    items {
        pushButton {
            text("First Button")
            clicks handledBy toast {
                content { div { +"First Button" } }
            }
        }
        pushButton {
            text("Second Button")
            clicks handledBy toast {
                content { div { +"Second Button" } }
            }
        }
    }
}
```

I must admit it is confusing, that autocompletion currently exposes the ``clicks`` event within the componen'ts context. I hope this will improve by solving Issue #323.

I hope I could help you so far. I will close this issue therefore.

**Closed by chausknecht** 2021-04-01 13:52 UTC
