### ISSUE TITLE
Min and max attributes on InputFieldComponent

### ISSUE THREAD

**Issue by Inkemann** [jwstegemann/fritz2#485] opened 2021-07-13 09:44 UTC
When using the InputFieldComponent the attributes min and max can not be set. Especially for dates this would be a valuable addition, because otherwise the built in date pickers let the user scroll infinitely both into the future and the past, which reduces the usability.

**Comment by chausknecht** [comment] 2021-07-13 20:15
The `InputField` (like other components that only wraps an HTML tag, see [item 415](Effective-fritz2-Components#item-415-consider-to-expose-the-wrapped-html-element-for-thin-wrappers) of EfC) exposes the underlying tag by the `element` property. So you can do the following:
```kotlin
inputField() {
    element {
        // access all properties of an input tag!
    }
}
```

Does this solve your issue?

Of course it is debateable whether to provide these properties directly within the component's DSL. Not shure how to separate the more important once from the minor important attributes though...

**Comment by chausknecht** [comment] 2021-08-02 07:10
I close this issue as enough time has passed by and ultimately this is not a bug :-)

**Closed by chausknecht** 2021-08-02 07:10 UTC
